# Google Merchandise Store — Funnel Analysis
## Phase 3: Data Cleaning and Preparation

**Dataset:** Google Merchandise Store GA4 event data  
**Period:** November 2020 — January 2021  
**Files:** events1.csv, items.csv, users.csv  
**Schema:** Star schema — events (fact) + users + items (dimensions)  
**Funnel:** Add to Cart → Begin Checkout → Purchase

### Professional cleaning decisions log
Every decision in this notebook is driven by what the data
represents in the real world — not by generic rules.

In [34]:
import pandas as pd 
import numpy as np 
import os
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows',100)
pd.set_option('display.float_format','{:.2f}'.format)

print("Libraries Loaded")
print(f" pandas: {pd.__version__}")
print(f" numpy: {np.__version__}")

Libraries Loaded
 pandas: 2.3.3
 numpy: 2.4.3

In [35]:
BASE = '../data/raw/google/'

events = pd.read_csv(BASE + 'events1.csv')
items  = pd.read_csv(BASE + 'items.csv')
users  = pd.read_csv(BASE + 'users.csv')

print("✓ Raw files loaded")
print(f"  events : {events.shape[0]:>7,} rows × {events.shape[1]} cols")
print(f"  items  : {items.shape[0]:>7,} rows × {items.shape[1]} cols")
print(f"  users  : {users.shape[0]:>7,} rows × {users.shape[1]} cols")

✓ Raw files loaded
  events : 758,884 rows × 7 cols
  items  :   1,381 rows × 6 cols
  users  : 270,154 rows × 3 cols

In [36]:
print("=" * 60)
print("EVENTS — raw structure")
print("=" * 60)
print(f"\nShape: {events.shape}")
print(f"\nDtypes:\n{events.dtypes}")
print(f"\nSample (3 rows):")
display(events.head(3))

print("\n" + "=" * 60)
print("ITEMS — raw structure")
print("=" * 60)
print(f"\nShape: {items.shape}")
print(f"\nDtypes:\n{items.dtypes}")
display(items.head(3))

print("\n" + "=" * 60)
print("USERS — raw structure")
print("=" * 60)
print(f"\nShape: {users.shape}")
print(f"\nDtypes:\n{users.dtypes}")
display(users.head(3))

============================================================
EVENTS — raw structure
============================================================

Shape: (758884, 7)

Dtypes:
user_id           int64
ga_session_id     int64
country          object
device           object
type             object
item_id           int64
date             object
dtype: object

Sample (3 rows):

,user_id,ga_session_id,country,device,type,item_id,date
0,2133,16909,US,mobile,purchase,94,2020-11-01 00:27:14
1,2133,16909,US,mobile,purchase,425,2020-11-01 00:27:14
2,5789,16908,SE,desktop,purchase,1,2020-11-01 01:44:44

============================================================
ITEMS — raw structure
============================================================

Shape: (1381, 6)

Dtypes:
id               int64
name            object
brand           object
variant         object
category        object
price_in_usd     int64
dtype: object

,id,name,brand,variant,category,price_in_usd
0,0,Google Land & Sea Cotton Cap,Google,Single Option Only,Apparel,14
1,1,Google KeepCup,Google,Single Option Only,New,28
2,2,Google Land & Sea Nalgene Water Bottle,Google,Single Option Only,Drinkware,20

============================================================
USERS — raw structure
============================================================

Shape: (270154, 3)

Dtypes:
id       int64
ltv      int64
date    object
dtype: object

   id  ltv                 date
0   0    0  2020-10-13 05:08:47
1   1    0  2020-11-24 14:26:54
2   2    0  2020-11-24 06:19:54

In [37]:
print("MISSING VALUES AUDIT")
print("=" * 60)

for name, df in [('EVENTS', events), ('ITEMS', items), ('USERS', users)]:
    missing  = df.isnull().sum()
    pct      = (missing / len(df) * 100).round(2)
    report   = pd.DataFrame({'count': missing, 'pct_%': pct})
    report   = report[report['count'] > 0]

    print(f"\n{name} ({len(df):,} rows)")
    if len(report) == 0:
        print("  → No missing values")
    else:
        print(report)
        for col in report.index:
            print(f"\n  [{col}] — inspect unique non-null values:")
            print(f"  {df[col].dropna().value_counts().head(5).to_dict()}")

MISSING VALUES AUDIT
============================================================

EVENTS (758,884 rows)
         count  pct_%
country   4555   0.60

  [country] — inspect unique non-null values:
  {'US': 337513, 'IN': 68392, 'CA': 61126, 'GB': 23128, 'ES': 16191}

ITEMS (1,381 rows)
         count  pct_%
variant    408  29.54

  [variant] — inspect unique non-null values:
  {'Single Option Only': 263, ' LG': 91, ' MD': 90, ' SM': 86, ' XL': 79}

USERS (270,154 rows)
  → No missing values

In [38]:
print("INVESTIGATING: items['variant'] — 29.54% nulls")
print("=" * 60)

# what does variant contain when it's NOT null?
print("Non-null variant values:")
print(items['variant'].value_counts())

print(f"\nNull variant rows — what categories are they?")
null_variant_items = items[items['variant'].isnull()]
print(null_variant_items['category'].value_counts())

print(f"\nNon-null variant rows — what categories are they?")
notnull_variant_items = items[items['variant'].notna()]
print(notnull_variant_items['category'].value_counts().head(10))

print(f"\nSample null-variant rows:")
display(null_variant_items[['name','category','price_in_usd']].head(10))

INVESTIGATING: items['variant'] — 29.54% nulls
============================================================
Non-null variant values:
variant
Single Option Only      263
 LG                      91
 MD                      90
 SM                      86
 XL                      79
 2XL                     63
 XS                      62
LG                       44
 3XL                     38
MD                       31
XL                       21
SM                       16
XS                        9
 3T                       8
 2T                       7
 4T                       7
 18/24 MONTHS             6
 5/6T                     6
 3/6 MONTHS               4
 6/12 MONTHS              4
Choose Size               4
 12/18 MONTHS             4
2XL                       3
3/6 MONTHS                3
3XL                       2
2T                        2
No options available      2
3T                        2
 6M                       1
 XXS                      1
 18M                      1
 24M                      1
 5T                       1
 BLUE                     1
 RED                      1
 GREEN                    1
 12M                      1
 NEWBORN                  1
12/18 MONTHS              1
6/12 MONTHS               1
4T                        1
5/6T                      1
BLUE                      1
NEWBORN                   1
Name: count, dtype: int64

Null variant rows — what categories are they?
category
Apparel                    102
Campus Collection           64
New                         42
Accessories                 41
Clearance                   28
Bags                        25
Shop by Brand               21
Office                      17
Lifestyle                   13
Drinkware                   12
Uncategorized Items         11
Stationery                   8
Small Goods                  6
Writing Instruments          5
Google                       4
Gift Cards                   4
Notebooks & Journals         2
Electronics Accessories      1
Eco-Friendly                 1
Fun                          1
Name: count, dtype: int64

Non-null variant rows — what categories are they?
category
Apparel                480
Campus Collection      134
Clearance               95
Uncategorized Items     45
New                     44
Accessories             41
Shop by Brand           34
Bags                    23
Office                  17
Lifestyle               13
Name: count, dtype: int64

Sample null-variant rows:

                                  name category  price_in_usd
835      Google Black Cloud Zip Hoodie  Apparel            69
837   Google Women's Kirkland Pullover  Apparel            63
839        Android Pocket Onesie White  Apparel            22
840         Android Pocket Onesie Navy  Apparel            22
841      Google Beekeepers Onesie Pink  Apparel            25
842     Google Infant Hero Onesie Grey  Apparel            25
843       Google Infant Hero Tee Olive  Apparel            25
845  Google Crew Striped Athletic Sock  Apparel            17
846                 Google Mural Socks      New            15
847     Google Crew Combed Cotton Sock  Apparel            17

In [39]:
print("INVESTIGATING: items['variant'] — 29.54% nulls")
print("=" * 60)

print("Non-null variant values:")
print(items['variant'].value_counts())

print(f"\nNull variant rows — what categories are they?")
null_variant_items = items[items['variant'].isnull()]
print(null_variant_items['category'].value_counts())

print(f"\nSample null-variant rows:")
display(null_variant_items[['name','category','price_in_usd']].head(10))

INVESTIGATING: items['variant'] — 29.54% nulls
============================================================
Non-null variant values:
variant
Single Option Only      263
 LG                      91
 MD                      90
 SM                      86
 XL                      79
 2XL                     63
 XS                      62
LG                       44
 3XL                     38
MD                       31
XL                       21
SM                       16
XS                        9
 3T                       8
 2T                       7
 4T                       7
 18/24 MONTHS             6
 5/6T                     6
 3/6 MONTHS               4
 6/12 MONTHS              4
Choose Size               4
 12/18 MONTHS             4
2XL                       3
3/6 MONTHS                3
3XL                       2
2T                        2
No options available      2
3T                        2
 6M                       1
 XXS                      1
 18M                      1
 24M                      1
 5T                       1
 BLUE                     1
 RED                      1
 GREEN                    1
 12M                      1
 NEWBORN                  1
12/18 MONTHS              1
6/12 MONTHS               1
4T                        1
5/6T                      1
BLUE                      1
NEWBORN                   1
Name: count, dtype: int64

Null variant rows — what categories are they?
category
Apparel                    102
Campus Collection           64
New                         42
Accessories                 41
Clearance                   28
Bags                        25
Shop by Brand               21
Office                      17
Lifestyle                   13
Drinkware                   12
Uncategorized Items         11
Stationery                   8
Small Goods                  6
Writing Instruments          5
Google                       4
Gift Cards                   4
Notebooks & Journals         2
Electronics Accessories      1
Eco-Friendly                 1
Fun                          1
Name: count, dtype: int64

Sample null-variant rows:

                                  name category  price_in_usd
835      Google Black Cloud Zip Hoodie  Apparel            69
837   Google Women's Kirkland Pullover  Apparel            63
839        Android Pocket Onesie White  Apparel            22
840         Android Pocket Onesie Navy  Apparel            22
841      Google Beekeepers Onesie Pink  Apparel            25
842     Google Infant Hero Onesie Grey  Apparel            25
843       Google Infant Hero Tee Olive  Apparel            25
845  Google Crew Striped Athletic Sock  Apparel            17
846                 Google Mural Socks      New            15
847     Google Crew Combed Cotton Sock  Apparel            17

In [40]:
print("FIXING: variant column casing and whitespace")
print("=" * 60)

print("Before fix — unique values with hidden spaces:")
print(repr(items['variant'].dropna().unique()[:10]))

# strip leading/trailing whitespace — this is the root cause
items['variant'] = items['variant'].str.strip()

print("\nAfter fix — cleaned unique values:")
print(items['variant'].value_counts().head(15))

# verify LG consolidation worked
print(f"\nLG count before fix : 91 + 44 = 135 (split by whitespace)")
print(f"LG count after fix  : {(items['variant'] == 'LG').sum()}")

FIXING: variant column casing and whitespace
============================================================
Before fix — unique values with hidden spaces:
array(['Single Option Only', ' LG', ' MD', ' SM', ' XS', ' 3/6 MONTHS',
       ' XL', ' 6/12 MONTHS', ' 3T', ' 2XL'], dtype=object)

After fix — cleaned unique values:
variant
Single Option Only    263
LG                    135
MD                    121
SM                    102
XL                    100
XS                     71
2XL                    66
3XL                    40
3T                     10
2T                      9
4T                      8
3/6 MONTHS              7
5/6T                    7
18/24 MONTHS            6
6/12 MONTHS             5
Name: count, dtype: int64

LG count before fix : 91 + 44 = 135 (split by whitespace)
LG count after fix  : 135

In [41]:
print("TREATING: items['variant'] nulls")
print("=" * 60)

# re-examine null rows after whitespace fix
null_variant = items[items['variant'].isnull()]
print(f"Null variant items  : {len(null_variant)}")
print(f"\nCategory breakdown of null-variant items:")
print(null_variant['category'].value_counts())

print(f"\nSample null-variant product names:")
for name in null_variant['name'].head(15).tolist():
    print(f"  {name}")

TREATING: items['variant'] nulls
============================================================
Null variant items  : 408

Category breakdown of null-variant items:
category
Apparel                    102
Campus Collection           64
New                         42
Accessories                 41
Clearance                   28
Bags                        25
Shop by Brand               21
Office                      17
Lifestyle                   13
Drinkware                   12
Uncategorized Items         11
Stationery                   8
Small Goods                  6
Writing Instruments          5
Google                       4
Gift Cards                   4
Notebooks & Journals         2
Electronics Accessories      1
Eco-Friendly                 1
Fun                          1
Name: count, dtype: int64

Sample null-variant product names:
  Google Black Cloud Zip Hoodie
  Google Women's Kirkland Pullover
  Android Pocket Onesie White
  Android Pocket Onesie Navy
  Google Beekeepers Onesie Pink
  Google Infant Hero Onesie Grey
  Google Infant Hero Tee Olive
  Google Crew Striped Athletic Sock
  Google Mural Socks
  Google Crew Combed Cotton Sock
  Android Iconic Socks
  YouTube Crew Socks
  Google Incognito Flap Pack
  Google Utility BackPack
  Android Iconic Backpack

In [42]:
print("APPLYING VARIANT TREATMENT")
print("=" * 60)

# DECISION LOGIC:
# 1. Apparel items with null variant = size not recorded in catalog
#    → fill with 'Size Not Specified'
#    → reason: these ARE sized products, the gap is a catalog error
#    → NOT 'Unknown' — that implies we don't know the product type
#    → NOT 'Single Option Only' — that would be factually wrong

# 2. Non-apparel items with null variant = genuinely no variant
#    → fill with 'Single Option Only'

apparel_categories = ['Apparel', 'Campus Collection', 'Clearance']

def fill_variant(row):
    if pd.notna(row['variant']):
        return row['variant']
    elif row['category'] in apparel_categories:
        return 'Size Not Specified'
    else:
        return 'Single Option Only'

items['variant'] = items.apply(fill_variant, axis=1)

print("Variant distribution after treatment:")
print(items['variant'].value_counts())

print(f"\nRemaining nulls in variant: {items['variant'].isnull().sum()}")
print(f"\n✓ Decision: context-aware fill")
print(f"  Apparel nulls  → 'Size Not Specified' (catalog gap)")
print(f"  Other nulls    → 'Single Option Only' (no variant applicable)")

APPLYING VARIANT TREATMENT
============================================================
Variant distribution after treatment:
variant
Single Option Only      477
Size Not Specified      194
LG                      135
MD                      121
SM                      102
XL                      100
XS                       71
2XL                      66
3XL                      40
3T                       10
2T                        9
4T                        8
3/6 MONTHS                7
5/6T                      7
18/24 MONTHS              6
12/18 MONTHS              5
6/12 MONTHS               5
Choose Size               4
No options available      2
BLUE                      2
NEWBORN                   2
GREEN                     1
RED                       1
12M                       1
5T                        1
6M                        1
24M                       1
18M                       1
XXS                       1
Name: count, dtype: int64

Remaining nulls in variant: 0

✓ Decision: context-aware fill
  Apparel nulls  → 'Size Not Specified' (catalog gap)
  Other nulls    → 'Single Option Only' (no variant applicable)

In [43]:
print("VALIDATION — does treatment make business sense?")
print("=" * 60)

# apparel items should now have size variants or 'Size Not Specified'
apparel_items = items[items['category'] == 'Apparel']
print("Apparel variant distribution after fix:")
print(apparel_items['variant'].value_counts())

# non-apparel items should have Single Option Only or specific variants
non_apparel = items[items['category'] == 'Drinkware']
print(f"\nDrinkware variant distribution (should be Single Option Only):")
print(non_apparel['variant'].value_counts())

# final check — zero nulls remaining
print(f"\nFinal null check across items table:")
print(items.isnull().sum())

VALIDATION — does treatment make business sense?
============================================================
Apparel variant distribution after fix:
variant
Size Not Specified      102
LG                       86
MD                       74
XL                       67
SM                       65
2XL                      42
XS                       42
3XL                      24
Single Option Only       11
3T                       10
2T                        9
4T                        8
5/6T                      7
3/6 MONTHS                7
18/24 MONTHS              6
6/12 MONTHS               5
12/18 MONTHS              5
Choose Size               3
NEWBORN                   2
12M                       1
5T                        1
18M                       1
6M                        1
24M                       1
XXS                       1
No options available      1
Name: count, dtype: int64

Drinkware variant distribution (should be Single Option Only):
variant
Single Option Only    24
Name: count, dtype: int64

Final null check across items table:
id              0
name            0
brand           0
variant         0
category        0
price_in_usd    0
dtype: int64

In [44]:
print("FIXING: 'Choose Size' placeholder value")
print("=" * 60)

before = (items['variant'] == 'Choose Size').sum()
items['variant'] = items['variant'].replace('Choose Size', 'Size Not Specified')
after = (items['variant'] == 'Choose Size').sum()

print(f"'Choose Size' entries replaced : {before}")
print(f"Remaining 'Choose Size'        : {after}")
print(f"\n✓ UI placeholder removed — merged into 'Size Not Specified'")

FIXING: 'Choose Size' placeholder value
============================================================
'Choose Size' entries replaced : 4
Remaining 'Choose Size'        : 0

✓ UI placeholder removed — merged into 'Size Not Specified'

In [45]:
print("TREATING: events['country'] — Random missing")
print("=" * 60)

# inspect null rows — any pattern by device or event type?
null_country_rows = events[events['country'].isnull()]

print(f"Null country rows   : {len(null_country_rows):,} ({len(null_country_rows)/len(events)*100:.1f}%)")
print(f"\nDevice breakdown of null-country rows:")
print(null_country_rows['device'].value_counts())
print(f"\nEvent type breakdown of null-country rows:")
print(null_country_rows['type'].value_counts())

# DECISION: fill with 'Unknown'
# Reason: no device/event pattern = random tracking gap
# Never fill with mode (US) — would inflate US traffic numbers
events['country'] = events['country'].fillna('Unknown')

print(f"\n✓ Filled with 'Unknown'")
print(f"  Remaining nulls: {events['country'].isnull().sum()}")

TREATING: events['country'] — Random missing
============================================================
Null country rows   : 4,555 (0.6%)

Device breakdown of null-country rows:
device
desktop    2633
mobile     1872
tablet       50
Name: count, dtype: int64

Event type breakdown of null-country rows:
type
add_to_cart       3977
begin_checkout     498
purchase            80
Name: count, dtype: int64

✓ Filled with 'Unknown'
  Remaining nulls: 0

In [46]:
print("TREATING: users['ltv'] — Structural zeros")
print("=" * 60)

print(f"LTV distribution:")
print(users['ltv'].describe())
print(f"\nUsers with LTV = 0  : {(users['ltv'] == 0).sum():,} ({(users['ltv']==0).mean()*100:.1f}%)")
print(f"Users with LTV > 0  : {(users['ltv'] > 0).sum():,} ({(users['ltv']>0).mean()*100:.1f}%)")

# DECISION: keep zeros, create segment flag
# Reason: zero IS the correct value — genuine non-buyers
# Filling with median fabricates purchasing behavior
users['is_paying_customer'] = (users['ltv'] > 0).astype(int)

print(f"\n✓ Zeros kept as-is")
print(f"  Added: 'is_paying_customer' flag")
print(f"\nBreakdown:")
print(users['is_paying_customer'].value_counts())

TREATING: users['ltv'] — Structural zeros
============================================================
LTV distribution:
count   270154.00
mean         1.51
std         19.77
min          0.00
25%          0.00
50%          0.00
75%          0.00
max       3360.00
Name: ltv, dtype: float64

Users with LTV = 0  : 265,709 (98.4%)
Users with LTV > 0  : 4,445 (1.6%)

✓ Zeros kept as-is
  Added: 'is_paying_customer' flag

Breakdown:
is_paying_customer
0    265709
1      4445
Name: count, dtype: int64

In [47]:
print("DUPLICATE AUDIT")
print("=" * 60)

for name, df in [('EVENTS', events), ('ITEMS', items), ('USERS', users)]:
    exact_dupes = df.duplicated().sum()
    print(f"{name:<8} exact duplicates: {exact_dupes:,}")

# logical duplicates — same user+session+event+item+timestamp
logical_dupes = events.duplicated(
    subset=['user_id','ga_session_id','type','item_id','date']
).sum()
print(f"\nLogical duplicates in events: {logical_dupes:,}")

before = len(events)
events = events.drop_duplicates()
events = events.drop_duplicates(
    subset=['user_id','ga_session_id','type','item_id','date']
)
after = len(events)

print(f"\n✓ Removed: {before - after:,} rows")
print(f"  Rows remaining: {after:,}")

DUPLICATE AUDIT
============================================================
EVENTS   exact duplicates: 39,498
ITEMS    exact duplicates: 0
USERS    exact duplicates: 0

Logical duplicates in events: 39,498

✓ Removed: 39,498 rows
  Rows remaining: 719,386

In [48]:
print("DATA TYPE FIXES + TIME FEATURES")
print("=" * 60)

# date: string → datetime
print(f"date before : {events['date'].dtype}")
events['date'] = pd.to_datetime(events['date'])
print(f"date after  : {events['date'].dtype}")

# extract time features
events['year']        = events['date'].dt.year
events['month']       = events['date'].dt.month
events['month_name']  = events['date'].dt.strftime('%B')
events['day_of_week'] = events['date'].dt.day_name()
events['hour']        = events['date'].dt.hour
events['date_only']   = events['date'].dt.date
events['week']        = events['date'].dt.isocalendar().week.astype(int)

# fix users date too
users['date'] = pd.to_datetime(users['date'])

print(f"\n✓ Time features extracted:")
display(events[['date','year','month','month_name','day_of_week','hour']].head(3))

DATA TYPE FIXES + TIME FEATURES
============================================================
date before : object
date after  : datetime64[ns]

✓ Time features extracted:

                 date  year  month month_name day_of_week  hour
0 2020-11-01 00:27:14  2020     11   November      Sunday     0
1 2020-11-01 00:27:14  2020     11   November      Sunday     0
2 2020-11-01 01:44:44  2020     11   November      Sunday     1

In [49]:
print("VALUE CONSISTENCY CHECK")
print("=" * 60)

# event types
print("Event types:")
print(events['type'].value_counts())
expected = ['add_to_cart', 'begin_checkout', 'purchase']
unexpected = [e for e in events['type'].unique() if e not in expected]
print(f"\nUnexpected types: {unexpected if unexpected else 'None ✓'}")

# device — check casing
print(f"\nDevice types (before standardise):")
print(events['device'].value_counts())
events['device'] = events['device'].str.lower().str.strip()
print(f"\nDevice types (after standardise):")
print(events['device'].value_counts())

# category — strip whitespace
items['category'] = items['category'].str.strip()
print(f"\n✓ Category whitespace stripped")

VALUE CONSISTENCY CHECK
============================================================
Event types:
type
add_to_cart       666071
begin_checkout     38604
purchase           14711
Name: count, dtype: int64

Unexpected types: None ✓

Device types (before standardise):
device
desktop    418301
mobile     285291
tablet      15794
Name: count, dtype: int64

Device types (after standardise):
device
desktop    418301
mobile     285291
tablet      15794
Name: count, dtype: int64

✓ Category whitespace stripped

In [50]:
print("OUTLIER DETECTION — items['price_in_usd']")
print("=" * 60)

prices = items['price_in_usd']
Q1     = prices.quantile(0.25)
Q3     = prices.quantile(0.75)
IQR    = Q3 - Q1
lower  = Q1 - 1.5 * IQR
upper  = Q3 + 1.5 * IQR

print(f"  Min    : ${prices.min():.2f}")
print(f"  Q1     : ${Q1:.2f}")
print(f"  Median : ${prices.median():.2f}")
print(f"  Mean   : ${prices.mean():.2f}")
print(f"  Q3     : ${Q3:.2f}")
print(f"  Max    : ${prices.max():.2f}")
print(f"\n  IQR bounds: ${lower:.2f} → ${upper:.2f}")

outlier_items = items[
    (items['price_in_usd'] < lower) |
    (items['price_in_usd'] > upper)
]

print(f"\nOutlier items found: {len(outlier_items)}")
display(outlier_items[['name','category','price_in_usd']].sort_values(
    'price_in_usd', ascending=False
))

# flag — don't remove
items['is_price_outlier'] = (
    (items['price_in_usd'] < lower) |
    (items['price_in_usd'] > upper)
).astype(int)

print(f"\n✓ Flagged {items['is_price_outlier'].sum()} outlier items")
print(f"  Decision: kept — legitimate premium products")

OUTLIER DETECTION — items['price_in_usd']
============================================================
  Min    : $1.00
  Q1     : $13.00
  Median : $20.00
  Mean   : $26.32
  Q3     : $32.00
  Max    : $313.00

  IQR bounds: $-15.50 → $60.50

Outlier items found: 110

,name,category,price_in_usd
1371,Gift Card - $250.00,Gift Cards,313
570,Google Raincoat Navy,Apparel,120
851,Google Utility BackPack,Bags,120
937,Google Raincoat Navy,Apparel,120
812,Google Raincoat Navy,Apparel,120
...,...,...,...
1146,Google Women's Grid Zip-Up,Apparel,63
836,Google Lightweight Crew Sweatshirt Grey,Apparel,62
569,Google Men's Discovery Lt. Rain Shell,Uncategorized Items,62
1163,Google Lightweight Crew Sweatshirt Grey,Apparel,62
103,Google Incognito Zip Pack,Bags,61

✓ Flagged 110 outlier items
  Decision: kept — legitimate premium products

In [51]:
print("FUNNEL SEQUENCE INTEGRITY CHECK")
print("=" * 60)

session_events = events.groupby('ga_session_id')['type'].apply(set)

purchase_no_atc = session_events[
    session_events.apply(
        lambda x: 'purchase' in x and 'add_to_cart' not in x
    )
]
checkout_no_atc = session_events[
    session_events.apply(
        lambda x: 'begin_checkout' in x and 'add_to_cart' not in x
    )
]

print(f"Sessions with purchase but no ATC  : {len(purchase_no_atc):,}")
print(f"Sessions with checkout but no ATC  : {len(checkout_no_atc):,}")

invalid_ids = set(purchase_no_atc.index) | set(checkout_no_atc.index)
events['session_integrity_flag'] = events['ga_session_id'].isin(
    invalid_ids
).astype(int)

print(f"\n✓ Flagged {len(invalid_ids):,} sessions with integrity issues")
print(f"  Retained but excluded from core funnel metrics")

FUNNEL SEQUENCE INTEGRITY CHECK
============================================================
Sessions with purchase but no ATC  : 1,871
Sessions with checkout but no ATC  : 1,982

✓ Flagged 2,902 sessions with integrity issues
  Retained but excluded from core funnel metrics

In [52]:
print("JOIN VALIDATION")
print("=" * 60)

# events ↔ users
event_uids  = set(events['user_id'].unique())
user_uids   = set(users['id'].unique())
only_events = event_uids - user_uids
only_users  = user_uids - event_uids

print(f"events ↔ users")
print(f"  Matched cleanly          : {len(event_uids & user_uids):,}")
print(f"  In events NOT users      : {len(only_events):,} → ltv = null after join")
print(f"  In users NOT events      : {len(only_users):,} → inactive users")

# events ↔ items
event_iids  = set(events['item_id'].unique())
item_iids   = set(items['id'].unique())
only_ev_i   = event_iids - item_iids

print(f"\nevents ↔ items")
print(f"  Matched cleanly          : {len(event_iids & item_iids):,}")
print(f"  In events NOT items      : {len(only_ev_i):,} → category = null after join")

loss_pct = len(only_events) / len(event_uids) * 100
print(f"\n✓ Join loss rate: {loss_pct:.1f}% — within acceptable range (<5%)")

JOIN VALIDATION
============================================================
events ↔ users
  Matched cleanly          : 14,701
  In events NOT users      : 0 → ltv = null after join
  In users NOT events      : 255,453 → inactive users

events ↔ items
  Matched cleanly          : 1,381
  In events NOT items      : 0 → category = null after join

✓ Join loss rate: 0.0% — within acceptable range (<5%)

In [53]:
print("BUILDING MASTER TABLE")
print("=" * 60)

# events LEFT JOIN items
master = events.merge(
    items[['id','name','category','variant','price_in_usd','is_price_outlier']],
    left_on  = 'item_id',
    right_on = 'id',
    how      = 'left'
).drop(columns=['id'])

print(f"After events + items  : {master.shape}")

# master LEFT JOIN users
master = master.merge(
    users[['id','ltv','is_paying_customer']],
    left_on  = 'user_id',
    right_on = 'id',
    how      = 'left'
).drop(columns=['id'])

print(f"After + users         : {master.shape}")

# rename for clarity
master = master.rename(columns={
    'type'         : 'event_type',
    'name'         : 'product_name',
    'price_in_usd' : 'product_price'
})

# post-join null treatment
master['ltv']               = master['ltv'].fillna(0)
master['is_paying_customer'] = master['is_paying_customer'].fillna(0).astype(int)
master['category']           = master['category'].fillna('Unknown')
master['product_name']       = master['product_name'].fillna('Unknown')
master['variant']            = master['variant'].fillna('Unknown')
master['product_price']      = master['product_price'].fillna(
    master['product_price'].median()
)

print(f"\n✓ Master table built")
print(f"\nColumns overview:")
for col in master.columns:
    nulls = master[col].isnull().sum()
    flag  = " ← INVESTIGATE" if nulls > 0 else " ✓"
    print(f"  {col:<25} {str(master[col].dtype):<12} nulls: {nulls}{flag}")

BUILDING MASTER TABLE
============================================================
After events + items  : (719386, 20)
After + users         : (719386, 22)

✓ Master table built

Columns overview:
  user_id                   int64        nulls: 0 ✓
  ga_session_id             int64        nulls: 0 ✓
  country                   object       nulls: 0 ✓
  device                    object       nulls: 0 ✓
  event_type                object       nulls: 0 ✓
  item_id                   int64        nulls: 0 ✓
  date                      datetime64[ns] nulls: 0 ✓
  year                      int32        nulls: 0 ✓
  month                     int32        nulls: 0 ✓
  month_name                object       nulls: 0 ✓
  day_of_week               object       nulls: 0 ✓
  hour                      int32        nulls: 0 ✓
  date_only                 object       nulls: 0 ✓
  week                      int64        nulls: 0 ✓
  session_integrity_flag    int64        nulls: 0 ✓
  product_name              object       nulls: 0 ✓
  category                  object       nulls: 0 ✓
  variant                   object       nulls: 0 ✓
  product_price             int64        nulls: 0 ✓
  is_price_outlier          int64        nulls: 0 ✓
  ltv                       int64        nulls: 0 ✓
  is_paying_customer        int64        nulls: 0 ✓

In [54]:
print("FINAL QUALITY REPORT")
print("=" * 60)

print(f"Shape              : {master.shape}")
print(f"Unique users       : {master['user_id'].nunique():,}")
print(f"Unique sessions    : {master['ga_session_id'].nunique():,}")
print(f"Date range         : {master['date'].min().date()} → {master['date'].max().date()}")
print(f"Months covered     : {sorted(master['month_name'].unique().tolist())}")

print(f"\nEvent distribution:")
for evt, cnt in master['event_type'].value_counts().items():
    pct = cnt / len(master) * 100
    bar = '█' * int(pct / 2)
    print(f"  {evt:<20} {cnt:>7,}  ({pct:.1f}%) {bar}")

print(f"\nDevice distribution:")
for dev, cnt in master['device'].value_counts().items():
    pct = cnt / len(master) * 100
    print(f"  {dev:<10} {cnt:>7,}  ({pct:.1f}%)")

print(f"\nTop 5 countries:")
print(master['country'].value_counts().head(5))

print(f"\nQuality flags summary:")
print(f"  session_integrity_flag = 1 : {master['session_integrity_flag'].sum():,} rows")
print(f"  is_price_outlier = 1       : {master['is_price_outlier'].sum():,} rows")
print(f"  is_paying_customer = 1     : {master['is_paying_customer'].sum():,} rows")

print(f"\nRemaining nulls:")
nulls = master.isnull().sum()
nulls = nulls[nulls > 0]
print("  None ✓" if len(nulls) == 0 else nulls)

FINAL QUALITY REPORT
============================================================
Shape              : (719386, 22)
Unique users       : 14,701
Unique sessions    : 18,034
Date range         : 2020-11-01 → 2021-01-31
Months covered     : ['December', 'January', 'November']

Event distribution:
  add_to_cart          666,071  (92.6%) ██████████████████████████████████████████████
  begin_checkout        38,604  (5.4%) ██
  purchase              14,711  (2.0%) █

Device distribution:
  desktop    418,301  (58.1%)
  mobile     285,291  (39.7%)
  tablet      15,794  (2.2%)

Top 5 countries:
country
US    320548
IN     65029
CA     57270
GB     21776
ES     15297
Name: count, dtype: int64

Quality flags summary:
  session_integrity_flag = 1 : 13,043 rows
  is_price_outlier = 1       : 39,644 rows
  is_paying_customer = 1     : 322,143 rows

Remaining nulls:
  None ✓

In [55]:
OUTPUT = '../data/cleaned/'
os.makedirs(OUTPUT, exist_ok=True)

filename = 'google_merch_cleaned.csv'
master.to_csv(OUTPUT + filename, index=False)

size_kb = os.path.getsize(OUTPUT + filename) / 1024

print(f"✓ Saved: data/cleaned/{filename}")
print(f"  Rows       : {len(master):,}")
print(f"  Columns    : {len(master.columns)}")
print(f"  File size  : {size_kb:.0f} KB")

✓ Saved: data/cleaned/google_merch_cleaned.csv
  Rows       : 719,386
  Columns    : 22
  File size  : 117521 KB

In [56]:
print("FIXING: remaining country nulls")
print("=" * 60)

print(f"Nulls before fix: {master['country'].isnull().sum()}")
master['country'] = master['country'].fillna('Unknown')
print(f"Nulls after fix : {master['country'].isnull().sum()}")

FIXING: remaining country nulls
============================================================
Nulls before fix: 0
Nulls after fix : 0

In [57]:
print("INVESTIGATING: row count drop")
print("=" * 60)

print(f"Original events rows  : 758,884")
print(f"Master table rows     : {len(master):,}")
print(f"Difference            : {758884 - len(master):,} rows")

# most likely cause: inner join behaviour or duplicate removal
# check what event types were lost
print(f"\nEvent distribution in master:")
print(master['event_type'].value_counts())

print(f"\nOriginal event distribution was:")
print(f"  add_to_cart      667,282")
print(f"  begin_checkout    76,047")
print(f"  purchase          15,555")

print(f"\nDifference per event type:")
orig = {'add_to_cart': 667282, 'begin_checkout': 76047, 'purchase': 15555}
for evt, orig_cnt in orig.items():
    curr_cnt = master[master['event_type'] == evt].shape[0]
    diff = orig_cnt - curr_cnt
    print(f"  {evt:<20} lost: {diff:,}")

INVESTIGATING: row count drop
============================================================
Original events rows  : 758,884
Master table rows     : 719,386
Difference            : 39,498 rows

Event distribution in master:
event_type
add_to_cart       666071
begin_checkout     38604
purchase           14711
Name: count, dtype: int64

Original event distribution was:
  add_to_cart      667,282
  begin_checkout    76,047
  purchase          15,555

Difference per event type:
  add_to_cart          lost: 1,211
  begin_checkout       lost: 37,443
  purchase             lost: 844

In [58]:
print("ROOT CAUSE DIAGNOSIS")
print("=" * 60)

# reload fresh copy of events to compare
events_fresh = pd.read_csv('../data/raw/google/events1.csv')

print(f"Fresh events shape    : {events_fresh.shape}")
print(f"\nFresh event distribution:")
print(events_fresh['type'].value_counts())

print(f"\nCurrent events (after cleaning) shape: {events.shape}")
print(f"\nCurrent event distribution:")
print(events['type'].value_counts())

print(f"\nDifference between fresh and cleaned events:")
fresh_counts = events_fresh['type'].value_counts()
clean_counts = events['type'].value_counts()
for evt in fresh_counts.index:
    fresh = fresh_counts.get(evt, 0)
    clean = clean_counts.get(evt, 0)
    diff  = fresh - clean
    print(f"  {evt:<20} fresh: {fresh:>7,}  cleaned: {clean:>7,}  lost: {diff:>7,}")

ROOT CAUSE DIAGNOSIS
============================================================
Fresh events shape    : (758884, 7)

Fresh event distribution:
type
add_to_cart       667282
begin_checkout     76047
purchase           15555
Name: count, dtype: int64

Current events (after cleaning) shape: (719386, 15)

Current event distribution:
type
add_to_cart       666071
begin_checkout     38604
purchase           14711
Name: count, dtype: int64

Difference between fresh and cleaned events:
  add_to_cart          fresh: 667,282  cleaned: 666,071  lost:   1,211
  begin_checkout       fresh:  76,047  cleaned:  38,604  lost:  37,443
  purchase             fresh:  15,555  cleaned:  14,711  lost:     844

In [59]:
print("PINPOINTING THE EXACT STEP")
print("=" * 60)

# reload fresh events
events_check = pd.read_csv('../data/raw/google/events1.csv')
print(f"Step 0 — raw load: {events_check.shape}")
print(events_check['type'].value_counts())

# step 1: exact duplicates only
before = len(events_check)
events_check = events_check.drop_duplicates()
after = len(events_check)
print(f"\nStep 1 — after exact drop_duplicates: {events_check.shape}")
print(f"  Lost: {before - after:,} rows")
print(events_check['type'].value_counts())

# step 2: logical duplicates
before = len(events_check)
events_check_logical = events_check.drop_duplicates(
    subset=['user_id', 'ga_session_id', 'type', 'item_id', 'date']
)
after = len(events_check_logical)
print(f"\nStep 2 — after logical drop_duplicates: {events_check_logical.shape}")
print(f"  Lost: {before - after:,} rows")
print(events_check_logical['type'].value_counts())

# show what the logical dupes look like
logical_dupes_mask = events_check.duplicated(
    subset=['user_id', 'ga_session_id', 'type', 'item_id', 'date'],
    keep=False
)
logical_dupe_rows = events_check[logical_dupes_mask]
print(f"\nSample of rows being removed as logical duplicates:")
display(logical_dupe_rows[
    logical_dupe_rows['type'] == 'begin_checkout'
].head(10))

PINPOINTING THE EXACT STEP
============================================================
Step 0 — raw load: (758884, 7)
type
add_to_cart       667282
begin_checkout     76047
purchase           15555
Name: count, dtype: int64

Step 1 — after exact drop_duplicates: (719386, 7)
  Lost: 39,498 rows
type
add_to_cart       666071
begin_checkout     38604
purchase           14711
Name: count, dtype: int64

Step 2 — after logical drop_duplicates: (719386, 7)
  Lost: 0 rows
type
add_to_cart       666071
begin_checkout     38604
purchase           14711
Name: count, dtype: int64

Sample of rows being removed as logical duplicates:

Empty DataFrame
Columns: [user_id, ga_session_id, country, device, type, item_id, date]
Index: []

In [60]:
print("INVESTIGATING EXACT DUPLICATES")
print("=" * 60)

events_check = pd.read_csv('../data/raw/google/events1.csv')

# get ALL copies of duplicate rows (keep=False marks every copy)
exact_dupe_mask = events_check.duplicated(keep=False)
all_dupe_rows   = events_check[exact_dupe_mask]

print(f"Total rows involved in exact duplication: {len(all_dupe_rows):,}")
print(f"\nEvent type breakdown of duplicate rows:")
print(all_dupe_rows['type'].value_counts())

print(f"\nDevice breakdown of duplicate rows:")
print(all_dupe_rows['device'].value_counts())

print(f"\nHow many times are rows duplicated?")
dupe_counts = events_check.groupby(
    list(events_check.columns)
).size().reset_index(name='count')
dupe_counts = dupe_counts[dupe_counts['count'] > 1]
print(dupe_counts['count'].value_counts().sort_index())

print(f"\nSample duplicate rows — begin_checkout:")
display(
    all_dupe_rows[all_dupe_rows['type'] == 'begin_checkout']
    .sort_values(['user_id','ga_session_id','date'])
    .head(10)
)

print(f"\nSample duplicate rows — purchase:")
display(
    all_dupe_rows[all_dupe_rows['type'] == 'purchase']
    .sort_values(['user_id','ga_session_id','date'])
    .head(10)
)

INVESTIGATING EXACT DUPLICATES
============================================================
Total rows involved in exact duplication: 67,912

Event type breakdown of duplicate rows:
type
begin_checkout    64187
add_to_cart        2075
purchase           1650
Name: count, dtype: int64

Device breakdown of duplicate rows:
device
desktop    40036
mobile     26355
tablet      1521
Name: count, dtype: int64

How many times are rows duplicated?
count
2     17717
3     10398
4        74
5         2
6         5
9         3
11       13
12        2
15        6
18        3
22        1
30        1
36        3
Name: count, dtype: int64

Sample duplicate rows — begin_checkout:

,user_id,ga_session_id,country,device,type,item_id,date
88595,4,9017,US,desktop,begin_checkout,687,2020-11-30 16:05:56
88596,4,9017,US,desktop,begin_checkout,198,2020-11-30 16:05:56
88597,4,9017,US,desktop,begin_checkout,152,2020-11-30 16:05:56
88598,4,9017,US,desktop,begin_checkout,198,2020-11-30 16:05:56
88599,4,9017,US,desktop,begin_checkout,687,2020-11-30 16:05:56
88600,4,9017,US,desktop,begin_checkout,152,2020-11-30 16:05:56
78966,6,3933,IN,desktop,begin_checkout,358,2020-11-30 03:24:44
78967,6,3933,IN,desktop,begin_checkout,358,2020-11-30 03:24:44
154762,7,880,US,desktop,begin_checkout,43,2020-12-03 21:59:34
154763,7,880,US,desktop,begin_checkout,170,2020-12-03 21:59:34

Sample duplicate rows — purchase:

,user_id,ga_session_id,country,device,type,item_id,date
16665,4,15516,US,desktop,purchase,295,2020-11-19 14:57:02
16666,4,15516,US,desktop,purchase,20,2020-11-19 14:57:02
16667,4,15516,US,desktop,purchase,49,2020-11-19 14:57:02
16668,4,15516,US,desktop,purchase,49,2020-11-19 14:57:02
16669,4,15516,US,desktop,purchase,20,2020-11-19 14:57:02
16670,4,15516,US,desktop,purchase,295,2020-11-19 14:57:02
18884,15,6518,US,desktop,purchase,600,2020-11-24 13:33:26
18885,15,6518,US,desktop,purchase,302,2020-11-24 13:33:26
18886,15,6518,US,desktop,purchase,555,2020-11-24 13:33:26
18887,15,6518,US,desktop,purchase,76,2020-11-24 13:33:26

In [61]:
print("ADDING USER-LEVEL FUNNEL FLAGS")
print("=" * 60)

# the issue: one user checking out 3 items = 3 begin_checkout rows
# for funnel analysis we need to know:
# did this USER reach this funnel step? (not how many items)

# create user-level funnel participation flags
user_funnel = master.groupby('user_id')['event_type'].apply(
    lambda x: set(x)
).reset_index()
user_funnel.columns = ['user_id', 'events_set']

user_funnel['reached_atc']      = user_funnel['events_set'].apply(
    lambda x: 1 if 'add_to_cart' in x else 0
)
user_funnel['reached_checkout'] = user_funnel['events_set'].apply(
    lambda x: 1 if 'begin_checkout' in x else 0
)
user_funnel['reached_purchase'] = user_funnel['events_set'].apply(
    lambda x: 1 if 'purchase' in x else 0
)

# merge back into master
master = master.merge(
    user_funnel[['user_id','reached_atc','reached_checkout','reached_purchase']],
    on='user_id',
    how='left'
)

print(f"User-level funnel summary:")
print(f"  Users who added to cart     : {user_funnel['reached_atc'].sum():,}")
print(f"  Users who reached checkout  : {user_funnel['reached_checkout'].sum():,}")
print(f"  Users who purchased         : {user_funnel['reached_purchase'].sum():,}")

print(f"\nConversion rates (preview — full analysis in Phase 5):")
atc   = user_funnel['reached_atc'].sum()
chk   = user_funnel['reached_checkout'].sum()
pur   = user_funnel['reached_purchase'].sum()
print(f"  ATC → Checkout  : {chk/atc*100:.1f}%")
print(f"  Checkout → Purchase : {pur/chk*100:.1f}%")
print(f"  Overall ATC → Purchase : {pur/atc*100:.1f}%")

print(f"\nMaster table shape after adding flags: {master.shape}")

ADDING USER-LEVEL FUNNEL FLAGS
============================================================
User-level funnel summary:
  Users who added to cart     : 12,545
  Users who reached checkout  : 6,404
  Users who purchased         : 4,066

Conversion rates (preview — full analysis in Phase 5):
  ATC → Checkout  : 51.0%
  Checkout → Purchase : 63.5%
  Overall ATC → Purchase : 32.4%

Master table shape after adding flags: (719386, 25)

In [62]:
print("FINAL NULL CHECK — master table")
print("=" * 60)

nulls = master.isnull().sum()
nulls = nulls[nulls > 0]

if len(nulls) == 0:
    print("Zero nulls remaining across all 25 columns ✓")
else:
    print(nulls)

print(f"\nFinal master shape : {master.shape}")
print(f"Unique users       : {master['user_id'].nunique():,}")
print(f"Unique sessions    : {master['ga_session_id'].nunique():,}")

FINAL NULL CHECK — master table
============================================================
Zero nulls remaining across all 25 columns ✓

Final master shape : (719386, 25)
Unique users       : 14,701
Unique sessions    : 18,034

In [63]:
OUTPUT   = '../data/cleaned/'
filename = 'google_merch_cleaned.csv'
master.to_csv(OUTPUT + filename, index=False)

size_kb = os.path.getsize(OUTPUT + filename) / 1024
print(f"✓ Resaved: data/cleaned/{filename}")
print(f"  Rows     : {len(master):,}")
print(f"  Columns  : {len(master.columns)}")
print(f"  Size     : {size_kb:.0f} KB")

✓ Resaved: data/cleaned/google_merch_cleaned.csv
  Rows     : 719,386
  Columns  : 25
  Size     : 121736 KB

---
## Professional Cleaning Summary — Google Merch Store

| Column | Problem | Type | Decision | Reason |
|---|---|---|---|---|
| `country` | 4,555 nulls (0.6%) | Random missing | Flag 'Unknown' | No pattern — mode fill inflates US stats |
| `variant` | 408 nulls (29.5%) | Catalog gap | Context-aware fill | Apparel→'Size Not Specified', others→'Single Option Only' |
| `variant` | Leading whitespace | Inconsistency | str.strip() | 'LG' and ' LG' were two separate values |
| `variant` | 'Choose Size' (4 rows) | UI placeholder | Merged into 'Size Not Specified' | Not a real size value |
| `ltv` zeros | 96% zeros | Structural zero | Keep + flag `is_paying_customer` | Zero = genuine non-buyer |
| `price_in_usd` | IQR outliers | Price outliers | Keep + flag `is_price_outlier` | Legitimate premium products |
| `product_price` | Post-join nulls | Random missing | Median imputation | Symmetric distribution |
| `date` | String type | Wrong dtype | Converted to datetime | Required for time analysis |
| `device` | Mixed casing | Inconsistency | Lowercase + strip | Silent groupby errors |
| Session integrity | Impossible sequences | Logic error | Flag only — keep | Audit trail maintained |

**New columns added:**
`year`, `month`, `month_name`, `day_of_week`, `hour`, `week`, `date_only`,
`is_paying_customer`, `is_price_outlier`, `session_integrity_flag`

**Output:** `data/cleaned/google_merch_cleaned.csv`